import 'package:flutter/material.dart';

import 'contact_models.dart';

const mockContacts = [
  Contact(
    id: 'u_qianli',
    name: '千里马',
    avatarLabel: '千',
    avatarColor: Color(0xFFE6332A),
    department: '外部协作',
    title: '产品顾问',
    email: 'qianli@example.com',
    status: 'online',
    isExternal: true,
    isFavorite: true,
  ),
  Contact(
    id: 'u_azhe',
    name: '阿拉蕾',
    avatarLabel: '阿',
    avatarColor: Color(0xFFFF7043),
    department: '产品研发部',
    title: 'AI 助手',
    email: 'azhe@example.com',
    status: 'online',
    isExternal: false,
    isFavorite: true,
  ),
  Contact(
    id: 'u_xiaoyu',
    name: '小宇',
    avatarLabel: '宇',
    avatarColor: Color(0xFF2F80ED),
    department: '前端体验组',
    title: 'Flutter 工程师',
    email: 'xiaoyu@example.com',
    status: 'busy',
    isExternal: false,
    isFavorite: false,
  ),
  Contact(
    id: 'u_ling',
    name: '林灵',
    avatarLabel: '林',
    avatarColor: Color(0xFF34A853),
    department: '设计中心',
    title: '交互设计师',
    email: 'linling@example.com',
    status: 'online',
    isExternal: false,
    isFavorite: false,
  ),
  Contact(
    id: 'u_miao',
    name: '妙搭助手',
    avatarLabel: '妙',
    avatarColor: Color(0xFF6C63FF),
    department: '机器人',
    title: '自动化助手',
    email: 'bot-miao@example.com',
    status: 'online',
    isExternal: false,
    isFavorite: false,
  ),
];
